server:
  port: 8081
spring:
  application:
    name: IM-Netty-WebSocket
  cloud:
    nacos:
      discovery:
        username: admin
        password: 123456
        server-addr: 182.168.80.1:15672
        service: ws-service
        group: DEFAULT_GROUP
        namespace: d1
  mvc:
    static-path-pattern: /static/**

ws-service:
  host: 0.0.0.0
  path: /ws-service
  port: 8082
