server:
  port: 8080
  servlet:
    context-path: /task
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.131:3306/supplier_center?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      connection-timeout: 20000
      max-lifetime: 1800000
      idle-timeout: 30000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除之前
      logic-not-delete-value: 0
      # 删除之后
      logic-delete-value: 1

user:
  task:
    core:
      poolSize: 5
    max:
      poolSize: 10
    queue:
      capacity: 1000
    keep:
      alive:
        seconds: 30
    thread:
      name:
        prefix: user-task-thread-

